### ISSUE TITLE
Broken SD-TV (720x576i) scaling (cutting / pause)

### ISSUE THREAD

**Issue by Quantomax** [pesintta/vdr-plugin-vaapidevice#86]
Hi,
if I cut SD Videos, e.g. seek Start and Stop of the movie with (1, 3, 4 and 6), I'll get an unscaled SD Picture in the top / left corner with some picture artifacts filling the rest of screen.  Occasionally I too loose OSD temporary or completely.

Seems too me, as this is the same effect, that makes the HD picture "jumpy" in cutting mode...

Nevertheless, thanks for the plugin!

Regards,
Stefan

**Comment by mighty-p** [comment]
Interesting, exactly the same happens for me with the current GIT for 720p programmes. Here, 576i and 1080i is OK, but maybe it's still related.

**Comment by mighty-p** [comment]
I played a bit around. As soon as I activate either Denoise or Sharpening (or both) for 720p in the menu (by setting a value >0), the scaling works. Without that, no postprocessing is done for 720p for me (since no interlace needed and I commented out the ColorBalance part). 

So the error seems to be that scaling is not happening when (for whatever reason) no postprocessing is running for a video format.

I wanted to double check, and changed video.c line 2562 from
    VaapiVideoProcessing = 1;
to
    // VaapiVideoProcessing = 1;
... and then indeed the scaling is not working anymore for all channels.

**Comment by mighty-p** [comment]
Since I am not sure if the problem that I noticed is exactly the same, I cut a separate issue (#95). I still suspect that both issues are related or have the same origin.

**Comment by pesintta** [comment]
Might have been fixed by https://github.com/pesintta/vdr-plugin-vaapidevice/commit/3f01e86445afe12af84166eeaf8c57595417386c. Can someone verify?

**Comment by Quantomax** [comment]
Unfortunately, the error is still present...

System info (vdr just restarted, paused cutting): 

#### VAAPIDEVICE SYSTEM INFORMATION REPORT
##### inxi
```
System:    Kernel: 4.14.10-dvb x86_64 bits: 64 gcc: 7.2.0 Console: tty 1 Distro: Debian GNU/Linux buster/sid
Machine:   Device: desktop Mobo: ASRock model: J3160-ITX serial: <filter>
           UEFI [Legacy]: American Megatrends v: P1.30 date: 03/30/2016
CPU:       Quad core Intel Celeron J3160 (-MCP-) arch: Airmont rev.4 cache: 1024 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 12800
           clock speeds: max: 2240 MHz 1: 1600 MHz 2: 1600 MHz 3: 1600 MHz 4: 1600 MHz
Graphics:  Card: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller
           bus-ID: 00:02.0
           Display Server: X.Org 1.19.6 driver: i915 Resolution: 1920x1080
           OpenGL: renderer: Mesa DRI Intel HD Graphics 400 (Braswell)
           version: 4.5 Mesa 17.3.6 Direct Render: Yes
Audio:     Card Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series High Definition Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: Advanced Linux Sound Architecture v: k4.14.10-dvb
```
##### vainfo
```
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Intel i965 driver for Intel(R) CherryView - 2.0.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
```
##### ffmpeg
```
ffmpeg version 3.4.2-1+b1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7 (Debian 7.3.0-4)
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100
```
##### gcc
```
7
```
##### svdrpsend
```
220 <filter> SVDRP VideoDiskRecorder 2.3.8; Sun Mar 11 19:54:47 2018; UTF-8
900- Frames: missed(0) duped(10938) dropped(39) total(406) PTS(16:26:04.434) drift(8888) audio(0) video(40)
900- Video: h264/vaapi_vld 720x576i 20:11 @ 1920x1080 - Intel i965 driver for Intel(R) CherryView - 2.0.0
900  Audio: ac3 48000Hz 6 channels
221 <filter> closing connection

Syslog claims:
Mar 11 19:51:55 roadrunner vdr: [7644] VAAPI: audio/alsa: using pass-through device 'hdmi:CARD=PCH,DEV=2,AES0=0x06'
vdr: [7644] VAAPI: audio/alsa: start delay 336ms
vdr: [7672] VAAPI-ERROR: Surface 0 query status = 0x6: invalid VASurfaceID
vdr: [7672] VAAPI-ERROR: Surface 0 query status = 0x6: invalid VASurfaceID
[each single key press 4/6]

Stefan
